version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3001:3001'
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    environment:
      - NUXT_PORT=3001
      - NUXT_HOST=0.0.0.0

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    networks:
      - app-network
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=portfolio_db
      - DB_DIALECT=mysql
      - PORT=3000

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio_db
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:
  node_modules:

networks:
  app-network:
